### PR TITLE
Add `dist-upgrade` to Node development section.

### PR DESCRIPTION
**Pull request by zautumnz**
`dist-upgrade` is a little script (which uses `npx` underneath) that updates global Node and npm. It's a bit of a silly package, but something I've had an alias for for ages. Using it via `npx` just makes it even sweeter.

- [x] I have read & abide by the CONTRIBUTING.md and CODE_OF_CONDUCT.md guidelines and agree to license my contributions as CC0-1.0.

type of change
=====
- [x] adding a tool / package / resource
  - please keep items sorted alphabetically
- [ ] a minor correction (spelling, broken link, name change)
- [ ] re-organization (please discuss on an issue before hand!)
- [ ] other

additional notes
=====

### CODE REVIEW

**Comment by junosuarez** [comment]
neat, and very useful idea. also, thank you for teaching me that `npx n <whatever>` works - this has instantly become part of my workflow!

I'm definitely willing to merge this, however I want to wait until https://github.com/zacanger/dist-upgrade/issues/1 is resolved.

cheers!

**Comment by zautumnz** [comment]
Should be fixed in 0.2.0, thanks to @zkat's generous help

**Comment by junosuarez** [comment]
Almost there :) I opened another issue: https://github.com/zacanger/dist-upgrade/issues/4

**Comment by zautumnz** [comment]
Fix released in 0.2.1 :)

**Comment by junosuarez** [comment]
made a small tweak to the description. thanks for the collaboration and fixing the bugs to get everything working!

**Comment by zautumnz** [comment]
Thank you!

**Pull request merged**
