### PR TITLE
add duhstar

### PR DESCRIPTION
**Pull request by davidguttman**
- [x] I have read & abide by the CONTRIBUTING.md and CODE_OF_CONDUCT.md guidelines and agree to license my contributions as CC0-1.0.

type of change
=====
- [x] adding a tool / package / resource
  - please keep items sorted alphabetically
- [ ] a minor correction (spelling, broken link, name change)
- [ ] re-organization (please discuss on an issue before hand!)
- [ ] other

additional notes
=====

### CODE REVIEW

**Comment by junosuarez** [comment]
Hi, thanks for opening this PR! It looks like a useful too, however I'm not going to merge this at this time. This is a new repo, and this is the first time I've had to reject an addition, so I want to provide some explanation, and to help establish criteria for future additions:

1. The name is non-obvious. One of the great things about npx is being able to have a wide array of programs available at your fingertips, based on your memory. This is useful to the extent that you can remember which commands you want to run! So, for inclusion in `awesome-npx`, I want to prioritize commands that are named after a well-known program (e.g., `figlet-cli`) or that are self-descriptive (e.g., `http-server`).

2. It is a brand new package. Just like [`awesome-list`](https://github.com/sindresorhus/awesome/blob/master/create-list.md) has a 30-day waiting period for adding new resources, I'd like to give a little more time to get a few users and get ay potential bugs sorted out. 30 days seems excessive, and I don't want to discourage people from making new things, but I think it's important to have unambiguous guidelines, so for `awesome-npx` we'll start with a 10 day waiting period- that's enough time to make something new and live with it for a few days, and maybe promote it through other channels, to establish how useful a tool is.

3. It is not cross-platform. One of the best parts about writing tools in Node.js rather than something like bash is that it is much easier to reach a wider audience, including Windows and other operating systems. A Node.js clone of an existing *nix utility would be a great candidate for inclusion in `awesome-npx` (e.g., `shx`)

In addition to these guidelines, a clear community interest would be reason to include a package in `awesome-npx`. An example would be a well-known or official tool, like `create-react-app`.

The purpose for these guidelines is to ensure the list includes high-quality, useful (or fun!) tools, and to encourage tool authors to create the same.

Thank you for your understanding!

**Comment by davidguttman** [comment]
I opened this PR because this was the first module that came to mind when reading about running commands with `npx` with no install. I've used it regularly for years, and now it's even better that it won't have to be reinstalled globally every time I'm on a new server or update node.

1. I've gone back and forth on the name. Right now its name is *exactly* what it is: `du -hs *` hard to get more non-obvious than that. However, maybe not useful for people not familiar with the command. So I agree, maybe a different name would be better.

2. This is not a new module, I just tweaked it before posting it here. This module has been around since 2014.

3. This is fair, shouldn't be too hard to make it cross-platform.

I would be happy to make the changes above (more friendly name, cross-platform). However, it would be nice to also include a guideline on "clear community interest" if that's going to be selection criteria. I assume it's not the 30k stars that `create-react-app` has?

**Comment by davidguttman** [comment]
Also, should a module have to meet all these points? I see at least one accepted module that only meets the first criteria.

**Comment by junosuarez** [comment]
> This is not a new module
You're right, my mistake :) I admit I just saw that all of the files on github had recently been recently modified, but that's not a great heuristic. Sorry!

As for clear community interest, it's hard to define. Certainly it's not 30,000 stars, but it probably means that it's popular enough to have blog posts about it, or discussion on twitter, etc. It's not *just* about popularity. If you can think of good criteria to more clearly define it, I'm open to it - I have an issue open at #13 

Also, closing this PR was maybe a bit hasty. I certainly didn't mean to say this tool could never be added to the list, just not in the current form for reasons 1 and 3 above. Thanks for contributing!

**Pull request closed without merging**
